name: flutter_msb
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  #轮播图
  flutter_swiper: ^1.1.6
  #网络请求库
  dio: ^2.1.5
  shared_preferences: 0.5.2+1
  synchronized: 2.1.0
  cached_network_image: ^0.7.0
  #webView
  flutter_webview_plugin: 0.3.5
  #路由
  fluro: ^1.5.0
  #视频播放
  video_player: ^0.10.0+2
  chewie: 0.9.7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/class_default.png
    - assets/images/ic_play.png
    - assets/images/ic_right_arrow.webp

